name=RFM6601W LoRa Module
version=1.0.0
author=Boardoza <eray.eroglu@boardoza.com>
maintainer=Boardoza <Boardoza.com>
sentence=Library for RFM6601W LoRa Module
paragraph=This library provides an easy-to-use API for interfacing with the RFM6601W LoRa module. It supports communication, initialization, and error handling. Designed for Arduino and PlatformIO projects, it includes example sketches and minimal dependencies.
category=Communication
url=https://github.com/Boardoza/Boardoza_RFM6601W_LoRa_Wireless_Breakout_Board
architectures=*